version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:password@db/cakephp_practise_db

  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cakephp_practise_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
